name: news_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

# isar_version: &isar_version 3.1.0
dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  meta: ^1.12.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
